// Curated skill presets grouped by role discipline. The UI exposes them as
// tabs; the resume stores whatever the user picks (or types) as plain strings
// in `resumes.skills`, so this list can grow without a migration.
export const SKILL_TABS: Array<{
  key: string;
  label: string;
  skills: string[];
}> = [
  {
    key: "design",
    label: "Design",
    skills: [
      "UI Design",
      "UX Design",
      "Product Design",
      "Interaction Design",
      "Visual Design",
      "Wireframing",
      "Prototyping",
      "User Research",
      "Usability Testing",
      "Design Systems",
      "Figma",
      "Sketch",
      "Adobe XD",
      "Framer",
      "Accessibility (a11y)",
      "Information Architecture",
      "Responsive Design",
      "Mobile Design",
      "Landing Page Design",
      "Dashboard Design",
    ],
  },
  {
    key: "engineering",
    label: "Engineering",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Python",
      "Go",
      "Rust",
      "Solidity",
      "Tailwind CSS",
      "HTML/CSS",
      "GraphQL",
      "REST APIs",
      "PostgreSQL",
      "Supabase",
      "Firebase",
      "MongoDB",
      "Docker",
      "Kubernetes",
      "AWS",
      "Vercel",
      "CI/CD",
      "Git",
      "Testing (Jest / Playwright)",
      "Performance Optimization",
      "Web3 / Ethereum",
      "Smart Contracts",
      "Wagmi / Viem",
      "Ethers.js",
      "The Graph",
    ],
  },
  {
    key: "brand",
    label: "Brand & Creative",
    skills: [
      "Branding",
      "Brand Strategy",
      "Brand Identity",
      "Logo Design",
      "Typography",
      "Illustration",
      "Iconography",
      "Motion Graphics",
      "Video Editing",
      "Premiere Pro",
      "After Effects",
      "3D Modelling",
      "Blender",
      "Cinema 4D",
      "Photography",
      "Art Direction",
      "Copywriting",
      "Storytelling",
    ],
  },
  {
    key: "product",
    label: "Product & PM",
    skills: [
      "Product Strategy",
      "Roadmapping",
      "Discovery",
      "User Interviews",
      "Go-to-Market",
      "A/B Testing",
      "Analytics",
      "SQL",
      "Mixpanel",
      "Amplitude",
      "Growth",
      "Agile",
      "Scrum",
      "Notion",
      "Linear",
      "Stakeholder Management",
    ],
  },
  {
    key: "ai",
    label: "AI & ML",
    skills: [
      "AI",
      "LLMs",
      "Prompt Engineering",
      "OpenAI API",
      "Anthropic API",
      "RAG",
      "Embeddings",
      "Vector Databases",
      "LangChain",
      "Model Fine-Tuning",
      "Machine Learning",
      "Computer Vision",
      "NLP",
      "PyTorch",
      "TensorFlow",
      "HuggingFace",
      "AI Agents",
    ],
  },
  {
    key: "marketing",
    label: "Marketing & Social",
    skills: [
      "Social Media Strategy",
      "Community Building",
      "Content Strategy",
      "SEO",
      "Paid Ads",
      "Email Marketing",
      "Influencer Outreach",
      "Partnership Management",
      "Web3 Community",
      "Twitter / X Growth",
      "Discord Moderation",
      "Telegram Management",
      "Event Management",
      "PR",
    ],
  },
];

export function allPresetSkills(): string[] {
  const out = new Set<string>();
  for (const tab of SKILL_TABS) for (const s of tab.skills) out.add(s);
  return Array.from(out);
}
