"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { CheckCircle2, CircleDollarSign, ImageIcon, Loader2, PackageCheck, Plus, Save, ToggleLeft, ToggleRight, Upload } from "lucide-react";
import { appAlert } from "@/lib/app-notify";
import { convertMerchPricesFromUsd, MERCH_CURRENCIES, normalizeMerchPrices, type MerchPrices, type MerchProduct } from "@/lib/merch-commerce";

const INPUT = "h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-[12px] text-[#0D1B39] outline-none transition focus:border-blue-400 focus:ring-4 focus:ring-blue-100";

function PriceInputs({ prices, onChange }: { prices: MerchPrices; onChange: (value: MerchPrices) => void }) {
  return <div className="space-y-2"><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{MERCH_CURRENCIES.map((currency) => <label key={currency} className="relative"><span className={`absolute left-3 top-1/2 -translate-y-1/2 text-[10px] font-bold ${currency === "USD" ? "text-[#0A4FE8]" : "text-slate-400"}`}>{currency}</span><input type="number" min="0" step="0.01" value={Number(prices[currency]) || ""} placeholder="Not set" onChange={(event) => { const amount = Math.max(0, Number(event.target.value) || 0); onChange(currency === "USD" ? convertMerchPricesFromUsd(amount, prices) : { ...prices, [currency]: amount }); }} className={`${INPUT} pl-12 ${currency === "USD" ? "border-blue-200 bg-blue-50/40" : ""}`} /></label>)}</div><p className="text-[10px] leading-4 text-slate-400">USD is the base price. Its equivalent is calculated for every supported currency and each result can still be adjusted manually.</p></div>;
}

export default function MerchCommercePage() {
  const [products, setProducts] = useState<MerchProduct[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState<string | null>(null);

  useEffect(() => { fetch("/api/admin/merch-config", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setProducts(payload.products || []); }).catch((error) => void appAlert(error.message || "Could not load Merch Commerce." )).finally(() => setLoading(false)); }, []);

  const update = (id: string, patch: Partial<MerchProduct>) => setProducts((current) => current.map((product) => product.id === id ? { ...product, ...patch } : product));
  const addProduct = () => {
    const key = typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}`;
    setProducts((current) => [...current, {
      id: `new-${key}`,
      code: `merch-${key}`,
      name: "New merch product",
      description: "",
      unit_label: "items",
      prices: normalizeMerchPrices({}),
      design_prices: normalizeMerchPrices({}),
      variants: { sizes: [], colors: [] },
      is_custom: false,
      active: true,
      sort_order: current.length * 10,
    }]);
    requestAnimationFrame(() => document.getElementById(`merch-new-${key}`)?.scrollIntoView({ behavior: "smooth", block: "center" }));
  };
  const save = async () => { setSaving(true); try { const response = await fetch("/api/admin/merch-config", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ products }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setProducts(payload.products || []); await appAlert("Merch catalogue, visuals and prices saved."); } catch (error) { await appAlert(error instanceof Error ? error.message : "Could not save Merch Commerce."); } finally { setSaving(false); } };
  const upload = async (id: string, file?: File) => { if (!file) return; setUploading(id); try { const form = new FormData(); form.append("file", file); form.append("catalogue", "merch"); const response = await fetch("/api/admin/catalog-presentation?catalogue=merch", { method: "POST", body: form }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); update(id, { presentation_image_path: payload.path, presentation_image_name: payload.fileName, presentation_image_url: payload.previewUrl }); } catch (error) { await appAlert(error instanceof Error ? error.message : "Could not upload the product presentation."); } finally { setUploading(null); } };

  if (loading) return <div className="grid min-h-[70vh] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#0A4FE8]" /></div>;
  return <div className="mx-auto max-w-[1500px] space-y-6 px-4 py-6 sm:px-6 lg:px-8">
    <header className="rounded-[24px] bg-[#0A4FE8] p-6 text-white shadow-[0_20px_60px_rgba(10,79,232,.18)] lg:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[11px] font-semibold text-blue-100">Sales Hub · Merch Commerce</p><h1 className="mt-2 text-[28px] font-bold tracking-tight lg:text-[36px]">Configure, present and price merchandise</h1><p className="mt-2 max-w-3xl text-[13px] leading-6 text-blue-50">Manage the client-facing catalogue, product presentations, variants, production prices and optional CDS Space design fees. Orders, quotations and invoices remain connected to the shared Sales Hub workflow.</p></div><div className="flex flex-wrap gap-3"><button onClick={addProduct} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl border border-white/60 bg-[#0A4FE8] px-6 text-[13px] font-bold text-white hover:bg-[#083FC2]"><Plus className="h-4 w-4" />Add merch</button><button onClick={save} disabled={saving} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-white px-6 text-[13px] font-bold text-[#0A4FE8] shadow-lg disabled:opacity-60">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Save changes</button></div></div></header>
    <div className="grid gap-4 sm:grid-cols-3">{[{ icon: PackageCheck, label: "Available products", value: products.filter((item) => item.active).length }, { icon: ImageIcon, label: "Presentation visuals", value: products.filter((item) => item.presentation_image_path).length }, { icon: CircleDollarSign, label: "Supported currencies", value: MERCH_CURRENCIES.length }].map((item) => <div key={item.label} className="rounded-[20px] border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-blue-50 text-[#0A4FE8]"><item.icon className="h-5 w-5" /></span><p className="mt-4 text-[25px] font-bold text-[#0D1B39]">{item.value}</p><p className="text-[12px] font-semibold text-[#0D1B39]">{item.label}</p></div>)}</div>
    <section className="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between lg:p-6"><div><h2 className="text-[16px] font-bold text-[#0D1B39]">Merch catalogue</h2><p className="mt-1 text-[12px] leading-5 text-slate-500">The product presentation is what clients see while choosing an item and whenever CDS Space is creating the print design.</p></div><button onClick={addProduct} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#0A4FE8] px-4 text-xs font-semibold text-white hover:bg-[#083FC2]"><Plus className="h-4 w-4" />Add merch</button></div><div className="divide-y divide-slate-100">{products.map((product) => <article id={`merch-${product.id}`} key={product.id} className="space-y-5 p-5 lg:p-6">
      <div className="grid gap-4 lg:grid-cols-[160px_1fr_auto]"><div className="relative h-36 overflow-hidden rounded-[18px] border border-slate-200 bg-slate-50">{product.presentation_image_url ? <Image src={product.presentation_image_url} alt={`${product.name} presentation`} fill unoptimized className="object-contain p-2" /> : <div className="grid h-full place-items-center px-4 text-center text-[10px] text-slate-400">Upload a clean product presentation</div>}</div><div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><input value={product.name} onChange={(event) => update(product.id, { name: event.target.value })} className={INPUT} /><input value={product.unit_label} onChange={(event) => update(product.id, { unit_label: event.target.value })} className={INPUT} placeholder="Unit label" /></div><textarea value={product.description || ""} onChange={(event) => update(product.id, { description: event.target.value })} className="min-h-20 w-full rounded-xl border border-slate-200 p-3 text-[12px] outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-100" placeholder="Client-facing description" /><label className="inline-flex h-9 cursor-pointer items-center gap-2 rounded-xl border border-blue-200 px-3 text-[11px] font-semibold text-[#0A4FE8] hover:bg-blue-50"><Upload className="h-3.5 w-3.5" />{uploading === product.id ? "Uploading…" : product.presentation_image_path ? "Replace visual" : "Upload visual"}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" disabled={uploading === product.id} onChange={(event) => void upload(product.id, event.target.files?.[0])} /></label></div><button type="button" onClick={() => update(product.id, { active: !product.active })} className={`inline-flex h-10 items-center gap-2 rounded-xl px-3 text-[11px] font-semibold ${product.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{product.active ? <ToggleRight className="h-4 w-4" /> : <ToggleLeft className="h-4 w-4" />}{product.active ? "Available" : "Hidden"}</button></div>
      {!product.is_custom && <div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1"><span className="text-[10px] font-semibold text-slate-500">Sizes, separated with commas</span><input value={(product.variants?.sizes || []).join(", ")} onChange={(event) => update(product.id, { variants: { ...product.variants, sizes: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) } })} className={INPUT} /></label><label className="space-y-1"><span className="text-[10px] font-semibold text-slate-500">Colours, separated with commas</span><input value={(product.variants?.colors || []).join(", ")} onChange={(event) => update(product.id, { variants: { ...product.variants, colors: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) } })} className={INPUT} /></label></div>}
      <div className="grid gap-4 xl:grid-cols-2"><div className="space-y-3 rounded-[18px] border border-blue-100 bg-blue-50/30 p-4"><h3 className="text-[12px] font-bold text-[#0D1B39]">Production price per {product.unit_label}</h3><PriceInputs prices={product.prices} onChange={(prices) => update(product.id, { prices })} /></div><div className="space-y-3 rounded-[18px] border border-violet-100 bg-violet-50/30 p-4"><h3 className="text-[12px] font-bold text-[#0D1B39]">Optional CDS Space design fee</h3><PriceInputs prices={product.design_prices} onChange={(design_prices) => update(product.id, { design_prices })} /></div></div>
    </article>)}</div></section>
    <div className="flex justify-end pb-8"><button onClick={save} disabled={saving} className="inline-flex h-12 items-center gap-2 rounded-2xl bg-[#0A4FE8] px-6 text-[13px] font-bold text-white shadow-lg shadow-blue-600/20 disabled:opacity-60">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />}Apply to Merch Studio</button></div>
  </div>;
}
