import { createHash, randomBytes } from "crypto";
import { NextResponse } from "next/server";
import { buildCMeetPath, normalizeCMeetTopic } from "@/lib/cmeet-links";
import { absolutePublicUrl } from "@/lib/public-site";
import { glashMaybeOne, glashQuery } from "@/lib/glashdb/postgres";

export const runtime="nodejs";

type ApiKey={id:string;client_user_id:string|null;scopes:string[];rate_limit_per_minute:number};
async function authenticate(req:Request){const raw=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"").trim()||"";if(!raw.startsWith("cmeet_live_"))return null;const hash=createHash("sha256").update(raw).digest("hex");const key=await glashMaybeOne<ApiKey>(`select id,client_user_id,scopes,rate_limit_per_minute from public.cmeet_api_keys where secret_hash=$1 and status='active' and (expires_at is null or expires_at>now()) limit 1`,[hash]);if(!key)return null;const count=await glashMaybeOne<{count:number}>(`select count(*)::int as count from public.cmeet_api_request_log where api_key_id=$1::uuid and created_at>now()-interval '1 minute'`,[key.id]);return Number(count?.count||0)>=key.rate_limit_per_minute?{key,limited:true}:{key,limited:false};}
function roomCode(){return `api-${randomBytes(8).toString("hex")}`;}
export async function POST(req:Request){const auth=await authenticate(req);if(!auth)return NextResponse.json({error:"Invalid or expired API key"},{status:401});if(auth.limited)return NextResponse.json({error:"Rate limit exceeded"},{status:429,headers:{"Retry-After":"60"}});if(!auth.key.scopes.includes("meetings:create"))return NextResponse.json({error:"Missing meetings:create scope"},{status:403});const body=await req.json().catch(()=>({}));const title=normalizeCMeetTopic(body.title);if(!title)return NextResponse.json({error:"Meeting title is required"},{status:400});const code=roomCode();const guestToken=randomBytes(24).toString("base64url");const now=new Date().toISOString();const [meeting]=await glashQuery<{id:string;room_code:string}>(`insert into public.team_meetings (room_code,title,audio_only,created_by_client,created_by_admin,guest_email,guest_token,api_key_id,status,started_at,approval_status,approved_at,approved_by_email) values ($1,$2,$3,$4::uuid,false,$5,$6,$7::uuid,'live',$8,'approved',$8,'cmeet-api') returning id,room_code`,[code,title,Boolean(body.audioOnly),auth.key.client_user_id,typeof body.hostEmail==="string"?body.hostEmail.slice(0,254):null,guestToken,auth.key.id,now]);await glashQuery(`update public.cmeet_api_keys set last_used_at=now() where id=$1::uuid`,[auth.key.id]);await glashQuery(`insert into public.cmeet_api_request_log (api_key_id,endpoint,response_status) values ($1::uuid,'POST /v1/cmeet/meetings',201)`,[auth.key.id]);const joinPath=buildCMeetPath(meeting.room_code,title);const hostPath=buildCMeetPath(meeting.room_code,title,guestToken);return NextResponse.json({id:meeting.id,roomCode:meeting.room_code,title,audioOnly:Boolean(body.audioOnly),joinUrl:absolutePublicUrl(joinPath),hostUrl:absolutePublicUrl(hostPath),createdAt:now},{status:201,headers:{"Cache-Control":"no-store"}});}
