import { redirect } from "next/navigation";
import { BadgePercent, ReceiptText } from "lucide-react";
import { MarketerShell } from "@/components/marketer/MarketerShell";
import { createClient } from "@/lib/glashdb/server";
import { getMarketerAccountState, marketerProfileComplete } from "@/lib/marketer-account";
import { formatMoney, type Currency } from "@/lib/finance/types";

export const dynamic = "force-dynamic";
export default async function MarketerEarningsPage() {
  const account = await getMarketerAccountState();
  if (!account) redirect("/marketer/login"); if (!account.agreement) redirect("/marketer/agreement"); if (!account.profile.billing_currency) redirect("/marketer/onboarding"); if (!marketerProfileComplete(account.profile)) redirect("/marketer/profile?setup=1");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = (await createClient()) as any;
  const { data } = await db.from("brand_marketer_commissions").select("*").eq("marketer_user_id", account.user.id).order("earned_at", { ascending: false });
  const rows = (data || []) as Array<{ id: string; client_name: string | null; invoice_number: string; invoice_total: number; commission_amount: number; commission_rate: number; currency: Currency; status: string; earned_at: string; paid_at: string | null }>;
  return <MarketerShell name={account.profile.display_name || account.profile.full_name || "Brand Marketer"} publicId={account.profile.public_id} code={account.profile.marketer_code}><header><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#075BE5]">Commission ledger</p><h1 className="mt-2 text-[32px] font-bold tracking-[-.03em]">Earnings</h1><p className="mt-2 text-[13px] text-[#667085]">A permanent invoice-level record of every 5% credit, payout and reversal.</p></header><section className="mt-7 overflow-hidden rounded-[16px] border border-[#DDE5F4] bg-white">{rows.length === 0 ? <div className="grid min-h-[360px] place-items-center p-8 text-center"><div><BadgePercent className="mx-auto size-10 text-[#C7D0E3]" /><p className="mt-4 text-[14px] font-semibold">No earnings yet</p><p className="mt-1 text-[11px] text-[#98A2B3]">A 5% entry appears when an attributed invoice is marked paid.</p></div></div> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="bg-[#F8FAFE] text-[10px] uppercase tracking-[.1em] text-[#98A2B3]"><tr><th className="px-5 py-3">Client / invoice</th><th className="px-5 py-3">Paid invoice</th><th className="px-5 py-3">Rate</th><th className="px-5 py-3">Your commission</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Earned</th></tr></thead><tbody className="divide-y divide-[#EDF0F6]">{rows.map((row) => <tr key={row.id} className="text-[12px]"><td className="px-5 py-4"><p className="font-semibold">{row.client_name || "CDS Space client"}</p><p className="mt-1 text-[10px] text-[#98A2B3]">{row.invoice_number}</p></td><td className="px-5 py-4">{formatMoney(row.invoice_total, row.currency)}</td><td className="px-5 py-4">5%</td><td className="px-5 py-4 font-bold text-emerald-600">{formatMoney(row.commission_amount, row.currency)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold uppercase ${row.status === "paid" ? "bg-emerald-50 text-emerald-700" : row.status === "reversed" ? "bg-red-50 text-red-600" : "bg-amber-50 text-amber-700"}`}>{row.status}</span></td><td className="px-5 py-4 text-[#667085]">{new Date(row.earned_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</section></MarketerShell>;
}
