"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, CreditCard, Eye, FilePenLine, Loader2, Package, Plus, Trash2, X } from "lucide-react";
import { appAlert, appConfirm } from "@/lib/app-notify";
import { formatMoney } from "@/lib/currency";
import { merchStatusLabel } from "@/lib/merch-commerce";

export interface MerchOrder {
  id: string; display_id?: string; title: string; status: string; quantity?: number; amount?: number; total?: number; currency?: string; created_at: string; updated_at: string;
  product_snapshot?: { name?: string; unit_label?: string }; presentation_image_url?: string | null; invoice_public_token?: string | null; invoice_status?: string | null;
  execution_mode?: string; fulfillment_type?: string; country?: string; state?: string; city?: string; recipient_name?: string; expected_delivery_at?: string | null; details?: Record<string, unknown>;
}

const tone: Record<string, string> = { DRAFT: "bg-slate-100 text-slate-600", AWAITING_QUOTE: "bg-violet-50 text-violet-700", AWAITING_PAYMENT: "bg-amber-50 text-amber-700", ACTIVE: "bg-blue-50 text-blue-700", COMPLETED: "bg-emerald-50 text-emerald-700", CANCELLED: "bg-red-50 text-red-600" };

export function MerchDashboard({ onCreateNew, onContinue }: { onCreateNew: () => void; onContinue: (id: string) => void }) {
  const [orders, setOrders] = useState<MerchOrder[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("ALL");
  const [selected, setSelected] = useState<MerchOrder | null>(null);
  const [broken, setBroken] = useState<Record<string, boolean>>({});
  const load = useCallback(() => fetch("/api/merch", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setOrders(payload.orders || []); }).catch((error) => void appAlert(error.message || "Could not load merchandise orders.")).finally(() => setLoading(false)), []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => filter === "ALL" ? orders : orders.filter((item) => item.status === filter), [filter, orders]);
  const active = orders.filter((item) => item.status === "ACTIVE").length;
  const completed = orders.filter((item) => item.status === "COMPLETED").length;
  const drafts = orders.filter((item) => item.status === "DRAFT").length;
  const deleteDraft = async (id: string) => { if (!await appConfirm("Delete this unfinished Merch Studio draft?")) return; const response = await fetch(`/api/merch/draft?id=${id}`, { method: "DELETE" }); const payload = await response.json().catch(() => ({})); if (!response.ok) return void appAlert(payload.error || "Could not delete the draft."); setOrders((current) => current.filter((item) => item.id !== id)); };

  return <div className="mx-auto w-full max-w-[1450px] space-y-6 p-3 sm:p-5 lg:p-8">
    <header className="rounded-[26px] border border-[#DDE5F4] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[11px] font-semibold text-[#0A4FE8]">Merch Commerce</p><h1 className="mt-1 text-[28px] font-bold tracking-tight text-[#07113F] sm:text-[34px]">Merch Studio</h1><p className="mt-1 text-[13px] text-slate-500">Create branded merchandise, pay securely and follow every order through production to delivery.</p></div><button onClick={onCreateNew} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-[#0A4FE8] px-6 text-[12px] font-bold text-white shadow-lg shadow-blue-600/20"><Plus className="h-4 w-4" />Create merch order</button></div>
      <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{ label: "All orders", value: orders.filter((item) => item.status !== "DRAFT").length, icon: Package, box: "bg-blue-50 text-blue-700" }, { label: "Active", value: active, icon: Clock3, box: "bg-violet-50 text-violet-700" }, { label: "Completed", value: completed, icon: CheckCircle2, box: "bg-emerald-50 text-emerald-700" }, { label: "Saved drafts", value: drafts, icon: FilePenLine, box: "bg-slate-100 text-slate-600" }].map((item) => <div key={item.label} className="rounded-[20px] border border-[#DDE5F4] p-5"><span className={`grid h-10 w-10 place-items-center rounded-xl ${item.box}`}><item.icon className="h-5 w-5" /></span><p className="mt-5 text-[28px] font-bold text-[#07113F]">{item.value}</p><p className="text-[11px] font-semibold text-slate-500">{item.label}</p></div>)}</div>
    </header>
    <section className="min-h-[480px] rounded-[26px] border border-[#DDE5F4] bg-white p-5 shadow-sm sm:p-7"><div className="flex gap-2 overflow-x-auto pb-4">{[["ALL","All"],["DRAFT","Drafts"],["AWAITING_QUOTE","Awaiting quote"],["AWAITING_PAYMENT","Awaiting payment"],["ACTIVE","Active"],["COMPLETED","Completed"]].map(([value,label]) => <button key={value} onClick={() => setFilter(value)} className={`whitespace-nowrap rounded-xl border px-4 py-2.5 text-[11px] font-semibold ${filter === value ? "border-[#0A4FE8] bg-[#0A4FE8] text-white" : "border-[#DDE5F4] text-slate-600 hover:border-blue-300"}`}>{label}</button>)}</div>
      {loading ? <div className="grid min-h-[330px] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#0A4FE8]" /></div> : filtered.length === 0 ? <div className="grid min-h-[360px] place-items-center text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-[#0A4FE8]"><Package className="h-7 w-7" /></span><h2 className="mt-4 text-[18px] font-bold text-[#07113F]">{orders.length ? "Nothing in this stage" : "No merchandise orders yet"}</h2><p className="mt-1 text-[12px] text-slate-500">Start an order or return to any saved draft when you are ready.</p><button onClick={onCreateNew} className="mt-5 h-11 rounded-xl bg-[#0A4FE8] px-5 text-[11px] font-bold text-white">Create merch order</button></div></div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((order) => <article key={order.id} className="overflow-hidden rounded-[22px] border border-[#DDE5F4] bg-white transition hover:-translate-y-0.5 hover:shadow-xl hover:shadow-blue-950/5"><div className="relative h-48 bg-[#EEF3FC]">{order.presentation_image_url && !broken[order.id] ? <Image src={order.presentation_image_url} alt={order.product_snapshot?.name || order.title} fill unoptimized onError={() => setBroken((current) => ({ ...current, [order.id]: true }))} className="object-contain p-4" /> : <div className="grid h-full place-items-center"><Package className="h-10 w-10 text-slate-300" /></div>}<span className="absolute left-4 top-4 rounded-lg bg-white px-2.5 py-1 text-[10px] font-bold text-[#07113F] shadow-sm">{order.display_id || `MRC-${order.id.slice(0,6)}`}</span></div><div className="space-y-4 p-5"><div><h3 className="text-[16px] font-bold text-[#07113F]">{order.title}</h3><p className="mt-1 text-[10px] text-slate-400">{order.product_snapshot?.name || "Merchandise"} · {order.quantity || 1} {order.product_snapshot?.unit_label || "items"}</p></div><div className="grid grid-cols-2 gap-4 border-y border-dashed border-slate-200 py-4"><div><p className="text-[9px] font-semibold text-slate-400">Value</p><p className="mt-1 text-[12px] font-bold text-[#07113F]">{Number(order.total || order.amount) > 0 ? formatMoney(Number(order.total || order.amount), order.currency || "NGN") : "Custom quote"}</p></div><div><p className="text-[9px] font-semibold text-slate-400">Updated</p><p className="mt-1 text-[12px] font-bold text-[#07113F]">{new Date(order.updated_at || order.created_at).toLocaleDateString()}</p></div></div><span className={`inline-flex rounded-full px-3 py-1.5 text-[10px] font-semibold ${tone[order.status] || "bg-slate-100 text-slate-600"}`}>{merchStatusLabel(order.status)}</span>
        {order.status === "DRAFT" ? <div className="grid grid-cols-[1fr_auto] gap-2"><button onClick={() => onContinue(order.id)} className="h-11 rounded-xl bg-[#0A4FE8] text-[11px] font-bold text-white">Continue draft</button><button onClick={() => void deleteDraft(order.id)} className="grid h-11 w-11 place-items-center rounded-xl border border-red-200 text-red-500 hover:bg-red-50"><Trash2 className="h-4 w-4" /></button></div> : <div className="grid grid-cols-2 gap-2">{order.status === "AWAITING_PAYMENT" && order.invoice_public_token ? <Link href={`/invoice/${order.invoice_public_token}#payment`} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#0A4FE8] text-[11px] font-bold text-white"><CreditCard className="h-4 w-4" />Pay now</Link> : <button onClick={() => setSelected(order)} className="h-11 rounded-xl border border-blue-200 text-[11px] font-bold text-[#0A4FE8]">Track order</button>}<button onClick={() => setSelected(order)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-[#DDE5F4] text-[11px] font-bold text-[#0D1B39]"><Eye className="h-4 w-4" />Details</button></div>}</div></article>)}</div>}
    </section>{selected && <OrderDetails order={selected} onClose={() => setSelected(null)} />}
  </div>;
}

function OrderDetails({ order, onClose }: { order: MerchOrder; onClose: () => void }) {
  const stages = ["AWAITING_PAYMENT", "ACTIVE", "COMPLETED"];
  const current = stages.indexOf(order.status);
  return <div className="fixed inset-0 z-[80] grid place-items-end bg-[#07113F]/50 p-0 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="max-h-[90vh] w-full overflow-y-auto rounded-t-[26px] bg-white p-6 sm:max-w-xl sm:rounded-[26px]"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-semibold text-[#0A4FE8]">{order.display_id}</p><h2 className="mt-1 text-[22px] font-bold text-[#07113F]">{order.title}</h2><p className="mt-1 text-[12px] text-slate-500">{order.product_snapshot?.name} · {order.quantity} {order.product_snapshot?.unit_label}</p></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><X className="h-4 w-4" /></button></div><div className="mt-7 space-y-3">{stages.map((stage, index) => { const reached = current >= index || order.status === "COMPLETED"; return <div key={stage} className={`flex items-center gap-3 rounded-[16px] border p-4 ${reached ? "border-blue-200 bg-blue-50/50" : "border-slate-200"}`}><span className={`grid h-8 w-8 place-items-center rounded-full ${reached ? "bg-[#0A4FE8] text-white" : "bg-slate-100 text-slate-400"}`}>{reached ? <CheckCircle2 className="h-4 w-4" /> : index + 1}</span><div><p className="text-[12px] font-bold text-[#0D1B39]">{stage === "AWAITING_PAYMENT" ? "Invoice and payment" : stage === "ACTIVE" ? "Order in production" : "Completed and delivered"}</p><p className="mt-0.5 text-[10px] text-slate-500">{stage === "ACTIVE" ? "CDS Space is currently processing your order." : stage === "COMPLETED" ? "The finished order has been handed over." : "Production starts automatically after payment is confirmed."}</p></div></div>; })}</div>{order.invoice_public_token && <Link href={`/invoice/${order.invoice_public_token}`} target="_blank" className="mt-6 inline-flex h-11 w-full items-center justify-center rounded-xl bg-[#0A4FE8] text-[11px] font-bold text-white">Open invoice</Link>}</div></div>;
}
