#!/usr/bin/env python3
"""
Regenerate src/lib/pdf/neue-campton-font.ts for the jsPDF documents.

jsPDF can only embed TTF (glyf) fonts, so this converts the Neue Campton OTFs
(CFF) to TTF, base64-encodes them, and records which code points the font
actually contains (used for the Helvetica fallback in src/lib/pdf/pdf-fonts.ts).

Run after dropping in the FULL licensed font (with complete glyph coverage) —
update the paths below if the filenames change:

    pip install fonttools otf2ttf
    python3 scripts/build-pdf-font.py
"""
import base64
from fontTools.ttLib import TTFont
from otf2ttf import cli

DIR = "public/font/neue-campton-font-family"
SRC = {
    "normal":     f"{DIR}/NeueCamptonTest-Regular-BF67089b6ea9633.otf",
    "bold":       f"{DIR}/NeueCamptonTest-Bold-BF67089b65d3e98.otf",
    "italic":     f"{DIR}/NeueCamptonTest-RegularItalic-BF67089b6eb3766.otf",
    "bolditalic": f"{DIR}/NeueCamptonTest-BoldItalic-BF67089b6e61f5b.otf",
}
OUT = "src/lib/pdf/neue-campton-font.ts"

b64, supported = {}, set()
for style, path in SRC.items():
    ttf = f"/tmp/nc-{style}.ttf"
    try:
        cli.main([path, "-o", ttf])
    except SystemExit:
        pass
    b64[style] = base64.b64encode(open(ttf, "rb").read()).decode()
    supported |= set(TTFont(path).getBestCmap().keys())
    print(f"{style}: ok")

cps = sorted(supported)
with open(OUT, "w") as out:
    out.write("// AUTO-GENERATED by scripts/build-pdf-font.py. Neue Campton TTFs for jsPDF,\n")
    out.write("// plus the code points the font contains (used for Helvetica fallback so no\n")
    out.write("// glyph ever renders as a blank box). Regenerate after installing the full\n")
    out.write("// licensed font (with complete glyph coverage) to drop the fallback.\n\n")
    out.write("export const NEUE_CAMPTON_TTF_B64 = {\n")
    for style in ("normal", "bold", "italic", "bolditalic"):
        out.write(f'  {style}: "{b64[style]}",\n')
    out.write("} as const;\n\n")
    out.write("export const NEUE_CAMPTON_CODEPOINTS: number[] = [\n  ")
    out.write(", ".join(str(c) for c in cps))
    out.write(",\n];\n")
print(f"wrote {OUT} ({len(cps)} code points)")
