import { createHash, randomBytes } from "crypto";
import { NextResponse } from "next/server";
import { getAdminSession } from "@/lib/admin-session";
import { glashQuery } from "@/lib/glashdb/postgres";

export const runtime="nodejs";
export const dynamic="force-dynamic";

async function superAdmin(){const session=await getAdminSession();return session?.role==="super_admin"?session:null;}

export async function GET(){const session=await superAdmin();if(!session)return NextResponse.json({ok:false,error:"Super admin access required"},{status:403});const [applications,keys]=await Promise.all([glashQuery(`select id,client_user_id,applicant_name,company_name,email,website,use_case,expected_monthly_calls,status,review_note,reviewed_at,created_at from public.cmeet_api_applications order by created_at desc`),glashQuery(`select key.id,key.application_id,key.client_user_id,key.name,key.key_prefix,key.scopes,key.rate_limit_per_minute,key.status,key.expires_at,key.last_used_at,key.created_at,app.email from public.cmeet_api_keys key left join public.cmeet_api_applications app on app.id=key.application_id order by key.created_at desc`)]);return NextResponse.json({ok:true,applications,keys});}

export async function POST(req:Request){const session=await superAdmin();if(!session)return NextResponse.json({ok:false,error:"Super admin access required"},{status:403});const body=await req.json().catch(()=>({}));const applicationId=String(body.applicationId||"");if(!applicationId)return NextResponse.json({ok:false,error:"Application required"},{status:400});const applications=await glashQuery<{id:string;client_user_id:string|null;email:string}>(`select id,client_user_id,email from public.cmeet_api_applications where id=$1::uuid limit 1`,[applicationId]);const application=applications[0];if(!application)return NextResponse.json({ok:false,error:"Application not found"},{status:404});const secret=`cmeet_live_${randomBytes(30).toString("base64url")}`;const prefix=secret.slice(0,18);const hash=createHash("sha256").update(secret).digest("hex");const scopes=Array.isArray(body.scopes)&&body.scopes.length?body.scopes.map(String):["meetings:create","meetings:read"];const [key]=await glashQuery(`insert into public.cmeet_api_keys (application_id,client_user_id,name,key_prefix,secret_hash,scopes,rate_limit_per_minute,issued_by,expires_at) values ($1::uuid,$2::uuid,$3,$4,$5,$6::text[],$7,$8,$9::timestamptz) returning id,name,key_prefix,scopes,rate_limit_per_minute,status,expires_at,created_at`,[application.id,application.client_user_id,String(body.name||"cMeet production key").trim().slice(0,120),prefix,hash,scopes,Math.max(1,Math.min(10000,Number(body.rateLimit)||60)),session.email,body.expiresAt||null]);await glashQuery(`update public.cmeet_api_applications set status='approved',reviewed_by=$2,reviewed_at=now(),updated_at=now() where id=$1::uuid`,[application.id,session.email]);return NextResponse.json({ok:true,key,secret,notice:"Copy this key now. For security, it will not be shown again."},{status:201});}

export async function PATCH(req:Request){const session=await superAdmin();if(!session)return NextResponse.json({ok:false,error:"Super admin access required"},{status:403});const body=await req.json().catch(()=>({}));if(body.keyId){await glashQuery(`update public.cmeet_api_keys set status='revoked',revoked_at=now() where id=$1::uuid`,[String(body.keyId)]);return NextResponse.json({ok:true});}const status=body.status==="approved"?"approved":"rejected";await glashQuery(`update public.cmeet_api_applications set status=$2,review_note=$3,reviewed_by=$4,reviewed_at=now(),updated_at=now() where id=$1::uuid`,[String(body.applicationId),status,String(body.note||"").trim().slice(0,2000)||null,session.email]);return NextResponse.json({ok:true});}
